service: aws

provider:
  name: aws
  runtime: python3.8

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy:
      - setuptools
      - boto3
      - botocore
      - s3transfer
    dockerizePip: non-linux
    slim: true

functions:
  hello:
    handler: handler.hello

package:
  exclude:
    - venv/**